CREATE TABLE ACCNT 
   (	ID NUMBER(5,0), 
	IBAN_TEXT VARCHAR2(30 BYTE), 
	ACCOUNT_TEXT VARCHAR2(30 BYTE), 
	BRANCH_NAME_TEXT VARCHAR2(100 BYTE), 
	FK_BANK_ID NUMBER(5,0), 
	FK_CURR_ID NUMBER(5,0), 
	FK_ACCOUNT_TYPE_ID NUMBER(5,0), 
	FK_COMPANY_ID NUMBER(5,0), 
	FK_ACCOUNT_STATUS_ID NUMBER(1,0), 
	FK_AUTO_TRANSFER_ID NUMBER(1,0)
   );
   
CREATE TABLE ACCOUNT_STATUS 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(30 BYTE)
   );
   
CREATE TABLE ACCOUNT_TYPE 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(50 BYTE)
   );
   
CREATE TABLE AUTO_TRANSFER 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(30 BYTE)
   );
   
CREATE TABLE BANK 
   (	ID NUMBER(5,0), 
	CODE_TEXT VARCHAR2(10 BYTE), 
	NAME_TEXT VARCHAR2(500 BYTE)
   );
   
CREATE TABLE COMPANY 
   (	ID NUMBER(5,0), 
	PARENT_ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(50 BYTE), 
	ADDRESS_TEXT VARCHAR2(500 BYTE), 
	CAPITAL_AMOUNT NUMBER(17,2)
   );
   
CREATE TABLE CURRENCY 
   (	ID NUMBER(5,0), 
	CODE_TEXT VARCHAR2(10 BYTE), 
	NAME_TEXT VARCHAR2(50 BYTE)
   );
   
CREATE TABLE DAILY_BALANCE 
   (	FK_ACCNT_ID NUMBER(5,0), 
	DATA_DATE DATE, 
	BALANCE_AMNT NUMBER(17,2)
   );
   
CREATE TABLE PAYMENT_RULE 
   (	ID NUMBER(5,0), 
	FK_PAYMENT_TYPE_ID NUMBER(5,0), 
	FK_BANK_ID NUMBER(5,0), 
	FK_WEEKDAY_ID NUMBER(5,0)
   );

CREATE TABLE PAYMENT_RULE_DTL 
   (	ID NUMBER(5,0), 
	FK_PAYMENT_RULE_ID NUMBER(5,0), 
	FK_WEEKDAY_ID NUMBER(5,0), 
	PERCENTAGE NUMBER(5,2)
   );

CREATE TABLE REF_TRXN 
   (	ID NUMBER(15,0), 
	FK_SUB_TRXN_TYPE_ID NUMBER(5,0)
   );

CREATE TABLE SUB_TRXN_TYPE 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(50 BYTE), 
	FK_TRXN_TYPE_ID NUMBER
   );   
   
CREATE TABLE TRXN 
   (	ID NUMBER(15,0), 
	REFERENCE_ID NUMBER(15,0), 
	ACCNT_ID NUMBER(15,0), 
	DEBIT_CREDIT_CODE VARCHAR2(1 BYTE), 
	TRXN_AMNT NUMBER(17,2), 
	TRXN_DATE DATE
   );
   
CREATE TABLE TRXN_TYPE 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(50 BYTE)
   );
   
CREATE TABLE WEEKDAY 
   (	ID NUMBER(5,0), 
	NAME_TEXT VARCHAR2(50 BYTE)
   );