insert into cmn_group(group_code,group_name,group_parent) values('sasia','South Asia','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('eur','Europe','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('mena','Middle East and North Africa','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('ssaf','Sub-Saharan Africa','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('sam','South America','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('easia','East Asia','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('nam','North America','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('cam','Central America','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('casia','Central Asia','GEO');
insert into cmn_group(group_code,group_name,group_parent) values('emr','Emerging Market','SPS');
insert into cmn_group(group_code,group_name,group_parent) values('prm','Prominent  Market','SPS');
insert into cmn_group(group_code,group_name,group_parent) values('erz','Eurozone','SPS');
insert into cmn_group(group_code,group_name,group_parent) values('frn','Frontier Market','SPS');
insert into cmn_group(group_code,group_name,group_parent) values('g20','G-20 Member','SPS');
insert into cmn_group(group_code,group_name,group_parent) values('lwinc','Low Income','INC');
insert into cmn_group(group_code,group_name,group_parent) values('uminc','Upper-Middle Income','INC');
insert into cmn_group(group_code,group_name,group_parent) values('lminc','Lower-Middle Income','INC');
insert into cmn_group(group_code,group_name,group_parent) values('hinc','High Income','INC');
insert into cmn_group(group_code,group_name,group_parent) values('lsdpd','Less Developed','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('est','Eastern Europe-Non EU','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngna','Developing North Africa','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngla','Developing Latin America','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dpd','Developed','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dpdeu','Developed-EU','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngme','Developing Middle East','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngas','Developing Asia','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngaf','Developing Africa','MKT');
insert into cmn_group(group_code,group_name,group_parent) values('dngeu','Developing-EU','MKT');
