insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Political Risk & Institutional Quality','priq','PR','PR:priq','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Corruption Perception','cp','PR','PR:cp','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Political Rights & Civil Liberties','prcl','PR','PR:prcl','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Democracy - Autocracy','da','PR','PR:da','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Participatory Governance','pg','PR','PR:pg','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Peace Atmosphere','pa','PR','PR:pa','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Government Consumption','gc','EF','EF:gc','Percentage (Total Counsumption)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Transfers Subsidies','ts','EF','EF:ts','Percentage (GDP)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Government Enterprises Investment','gei','EF','EF:gei','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Top Marginal Income Tax Rate','tmitr','EF','EF:tmitr','Percentage');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Top Marginal Income Payroll Tax Rate','tmiptr','EF','EF:tmiptr','Percentage');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Government Size','gs','EF','EF:gs','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Judicial Independence','ji','EF','EF:ji','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Impartial Courts','ic','EF','EF:ic','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Protection of Property Rights','ppr','EF','EF:ppr','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values (' Military Interference Rule of Law Politics','mi','EF','EF:mi','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Legal System Integrity','lsi','EF','EF:lsi','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Legal Enforcement of Contracts','lec','EF','EF:lec','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Regulatory Restrictions - Sale Real Property','rrsrp','EF','EF:rrsrp','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Reliability of Police','rp','EF','EF:rp','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Business Costs of Crime','bcc','EF','EF:bcc','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Legal System & Property Rights','lspr','EF','EF:lspr','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Money Growth M1','mgm1','EF','EF:mgm1','Percentage');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Standard Deviation of Inflation','sdi','EF','EF:sdi','Rate');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Inflation','inf','EF','EF:inf','Percentage');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Freedom - Own Foreign Currency Bank Accounts','fofcba','EF','EF:fofcba','Index(0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Sound Money','sm','EF','EF:sm','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Revenue Trade Tax','rtt','EF','EF:rtt','Percentage (International Trade)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Mean Tariff','mt','EF','EF:mt','Rate');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Standard Deviation of Tariff Rates','sdtr','EF','EF:sdtr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Non Tariff Trade Barriers','nttb','EF','EF:nttb','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Compliance Cost Importing Exporting','ccie ','EF','EF:ccie ','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Regulatory Trade Barriers','rtb','EF','EF:rtb','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Black Market Exchange','bme','EF','EF:bme','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Foreign Ownership Investment Restrictions','foir','EF','EF:foir','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Capital Control','cc','EF','EF:cc','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Freedom - Foreigners Visit','ffv','EF','EF:ffv','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Controls Movement Capital People','cmcp ','EF','EF:cmcp ','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('International Trade Freedom','itf','EF','EF:itf','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Banks Ownership','bo','EF','EF:bo','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Private Sector Credit','psc','EF','EF:psc','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Interest Rate Controls / Negative Real Interest Rates','ircn','EF','EF:ircn','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Credit Market Regulation','cmr','EF','EF:cmr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Hiring Regulations Minimum Wage','hrmw','EF','EF:hrmw','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Hiring - Firing Regulation','hfr','EF','EF:hfr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Centralized Collective Bargaining','ccb','EF','EF:ccb','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Hours Regulation','hr','EF','EF:hr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Mandated Cost Worker Dismissal','mcwd','EF','EF:mcwd','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Conscription','csc','EF','EF:csc','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Labor Market Regulation','lmr','EF','EF:lmr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Administrative Requirements','ar','EF','EF:ar','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Bureaucracy Costs','bc','EF','EF:bc','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Starting Business','sb','EF','EF:sb','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Extra Payments / Bribes / Favoritism','epbf','EF','EF:epbf','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Licensing Restrictions','lr','EF','EF:lr','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Tax Compliance','tc','EF','EF:tc','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Business Regulations','br','EF','EF:br','Index (0-10)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Regulations','rgl','EF','EF:rgl','Index (0-100)');
insert cmn_indicator (_name,api_code,source_code,_code,unit) values ('Economic Freedom','ef','EF','EF:ef','Index (0-100)');
