insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (34,'Southern Asia',142);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (154,'Northern Europe',150);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (39,'Southern Europe',150);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (15,'Northern Africa',2);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (61,'Polynesia',9);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (17,'Middle Africa',2);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (29,'Caribbean',19);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (5,'South America',19);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (145,'Western Asia',142);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (53,'Australia and New Zealand',9);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (155,'Western Europe',150);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (151,'Eastern Europe',150);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (13,'Central America',19);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (11,'Western Africa',2);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (21,'Northern America',19);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (18,'Southern Africa',2);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (35,'South-Eastern Asia',142);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (14,'Eastern Africa',2);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (30,'Eastern Asia',142);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (54,'Melanesia',9);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (57,'Micronesia',9);
insert into cmn_sub_continent(sub_continent_id,sub_continent_name,continent_id) values (143,'Central Asia',142);
